[logger]
keys = ["root"]

[handler]
keys = ["file"]

[formatter]
keys = ["mainFormatter"]

[logger.root]
level = "DEBUG"
handlers = ["file"]

[handler.file]
class = "FileHandler"
formatter = "mainFormatter"
level = "DEBUG"

[formatter.mainFormatter]
format = "%(asctime)s - %(module)s - %(levelname)s - %(message)s"